version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      google-cloud:
        patterns:
          - "cloud.google.com/go/*"
          - "google.golang.org/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
