version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosec
    - bodyclose
    - noctx
    - sqlclosecheck
    - gocritic
    - errorlint
    - misspell
    - copyloopvar

  settings:
    govet:
      disable:
        - fieldalignment
    errcheck:
      check-type-assertions: true
    gosec:
      excludes: []

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
